language: php

php:
    - 5.6
      env: PHPUNIT_FLAGS="--coverage-clover coverage.clover" CHECK_CS=true

services: mongodb

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install --dev
