services: mongodb

language: php

php:
    - 5.3
    - 5.4
    - 5.5

services: mongodb

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install --dev
